<?php

function modcomment_form_alter(&$form, &$form_state, &$form_id) {
    // print_r($form_id);
    // print_r("<br>");

    if($form_id == 'comment_node_page_form') {
        // print '<pre>';
        // print_r ($form);
        // print '<pre>';

        //remove the subject field
        unset($form['subject']);

        //hide user name in comment form
        $form['author']['_author']['#default_value'] = 0;
    }
}
